on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      # Let all jobs run to completion -- this will allow us to determine if
      # the failure is specific to a Racket version.
      fail-fast: false
      matrix:
        racket-version: ["7.8", "current"]
        racket-variant: ["regular", "CS"]
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v0.10
        with:
          architecture: x64
          distribution: minimal
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}

      # Setup this source repository as a package catalog which has higher
      # priority than the main catalog

      - run: racket -l- pkg/dirs-catalog --link catalog .
      - run: echo "file://`pwd`/catalog" > catalogs.txt
      - run: raco pkg config catalogs >> catalogs.txt
      - run: raco pkg config --set catalogs `cat catalogs.txt`
      - run: raco pkg config catalogs

      # Install plot and its dependencies.  Since we installed minimal racket,
      # this will fetch most of the packages from the main package catalog,
      # except for the packages inside this directory, which have higher
      # priority.

      - run: sudo raco pkg install --batch --auto plot

      # This runs any tests inside the plot, plot-lib, plot-gui-lib and
      # plot-doc packages, but NOT the plot-test package.  The actual tests
      # are in the `plot-test` package, so we don't expect any tests here, but
      # just in case someone wrote a test module...

      - run: sudo xvfb-run raco test --deps --package plot

      # Install the plot-test package and run the tests
        
      - run: sudo raco pkg install --batch --auto plot-test
      - run: sudo xvfb-run raco test --package plot-test

      # If any of the plot-test tests failed, they will generate new draw step
      # files and sample images.  Upload these as an Github Actions Artifact,
      # so they can be inspected by the developer.
      
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: New Test Data Files ${{ matrix.racket-version }} ${{ matrix.racket-variant }}
          path: plot-test/plot/tests/**/test-data/new-*
